### ISSUE TITLE
minor bug in chain names

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/docs#277]
<img width="698" alt="image" src="https://github.com/zeta-chain/docs/assets/88689859/ebacd0ae-972e-4aa7-98d0-530ea603d16a">

https://www.zetachain.com/docs/architecture/observers/

**Comment by fadeev** [comment]
Hm, I can't see this 😬

<img width="1840" alt="Screenshot 2024-03-01 at 18 23 42" src="https://github.com/zeta-chain/docs/assets/332151/f9f5ea5f-d6a8-46d3-b267-f44015caa2aa">
