### ISSUE TITLE
Can't sync with a snapshot

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/docs#293]
```
7:14PM ERR Error in validation err="wrong Block.Header.AppHash.  Expected 24B8913BEE5A6725C9D293A79C6035D56865FD104F7872360C3BBCC7F8A3473F, got 71234A360967F769B4FBB5762EB14C92F0985107E2671CCCFEB991F5D616EAC6" module=blockchain server=node
7:14PM ERR Stopping peer for error err="blockchainReactor validation error: wrong Block.Header.AppHash.  Expected 24B8913BEE5A6725C9D293A79C6035D56865FD104F7872360C3BBCC7F8A3473F, got 71234A360967F769B4FBB5762EB14C92F0985107E2671CCCFEB991F5D616EAC6" module=p2p peer={"Data":{},"Logger":{}} server=node
7:14PM INF service stop impl={"Data":{},"Logger":{}} module=p2p msg={} peer={"id":"c3b31e9ae42fdc3ce0eea91bf819707e641c05dd","ip":"16.62.137.114","port":26656} server=node
7:14PM INF service stop impl={"Logger":{}} module=p2p msg={} peer={"id":"c3b31e9ae42fdc3ce0eea91bf819707e641c05dd","ip":"16.62.137.114","port":26656} server=node
7:14PM ERR Stopping peer for error err="blockchainReactor validation error: wrong Block.Header.AppHash.  Expected 24B8913BEE5A6725C9D293A79C6035D56865FD104F7872360C3BBCC7F8A3473F, got 71234A360967F769B4FBB5762EB14C92F0985107E2671CCCFEB991F5D616EAC6" module=p2p peer={"Data":{},"Logger":{}} server=node
```

![image](https://github.com/zeta-chain/docs/assets/332151/e98e0bb1-05fa-456f-875e-86426b2bed8e)

```
2:26AM INF invalid peer blockHeight=2047738 module=blockchain peer=705578c35cab12f886559951df65b419d179c0a8 server=node
2:27AM INF Inbound Peer rejected err="auth failure: handshake failed: EOF" module=p2p numPeers=12 server=node
2:27AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=12 numToDial=48 server=node
can not find any peer with income
```

Following these instructions:

https://www.zetachain.com/docs/validators/setup/

https://www.zetachain.com/docs/validators/snapshot/

**Comment by fadeev** [comment]
@gzukel @CryptoFewka

**Comment by CryptoFewka** [comment]
What snapshot was used?

**Comment by CryptoFewka** [comment]
Based on the screenshot, the snapshot is likely Mainnet and is before from before the v14.0.1 upgrade. If the node operator is attempting to start the node a binary other than zetacored v12.2.x, it will not succeed.

I recommend the node operator start the node from this particular snapshot with either the v12.2.6 or v12.2.0 zetacored binary. At the Mainnet v14 upgrade height (2074730), the zetacored binary should be switched by the operator to v14.0.1. Cosmovisor can be used to automate the switch, or it can be done manually.

**Comment by fadeev** [comment]
Would it be possible to add a zetacored version that is compatible with the snapshot in the API response?

https://snapshots.zetachain.com/latest-snapshot?network=mainnet

Right now it's not clear: we're telling users to install the latest version of the binary, but then the snapshot is only compatible with an old version.
