### ISSUE TITLE
Update the Keplr docs

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/docs#371]
Keplr docs on https://www.zetachain.com/docs/users/

Keplr now natively supports ZetaChain, which brings additional features that we can cover in the docs.

* To add ZetaChain Mainnet Beta, go to menu in the extension and "Manage Chain Visibility"
* To add ZetaChain Testnet, go to https://chains.keplr.app/ and add the chain
* Update the Transfer Tokens with screenshots with mainnet
* Add a doc on staking with screenshots
* Add a doc on voting on governance proposals

ZetaChain testnet is also available on https://testnet.keplr.app/chains/zetachain-athens-3-testnet

**Comment by lukema95** [comment]
How do I transfer native ZETA assets to zetaxxx address in Keplr?

**Comment by fadeev** [comment]
@lukema95 `zeta***` and `0x***` derived from the same public key represent the same account, so you don't need to transfer, the same balance should show up on both.

https://www.zetachain.com/docs/developers/evm/addresses/

**Comment by lukema95** [comment]
> @lukema95 `zeta***` and `0x***` derived from the same public key represent the same account, so you don't need to transfer, the same balance should show up on both.
> 
> https://www.zetachain.com/docs/developers/evm/addresses/

Got it. I could complete this issue.
