### ISSUE TITLE
Move ZetaAI button to the search bar

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/docs#429]
Like so:

<img width="580" alt="Screenshot 2024-08-05 at 20 07 53" src="https://github.com/user-attachments/assets/cef82d39-63af-4ac3-a445-2eef516fd362">

To avoid this:

<img width="428" alt="Screenshot 2024-08-05 at 20 09 15" src="https://github.com/user-attachments/assets/52e71d07-f064-4b67-8aac-6f998a077157">

**Comment by bbbeeeee** [comment]
+1!
