### ISSUE TITLE
UI: supporting sub sections in the navigation bar

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/docs#459]
Currently only the high level section are listed in the navigation bar:
- Build
- Run a Node 
- Use

Which makes the docs a bit hard to navigate and see where you're at.

I think we should list sub section in the navigation bar, eventually having it collapsable.

Also the high section names collapse when entering a sub section, I think this behavior makes it harder to navigate the docs as well.

**Comment by fadeev** [comment]
I agree that we need to improve navigation in the docs, but I don't think cramming navigation into a narrow column on the left (sidebar) is a solution.

**Comment by lumtis** [comment]
>  I don't think cramming navigation into a narrow column on the left (sidebar) is the solution.

I honestly don't see an issue with this
