### ISSUE TITLE
A page for displaying network upgrades

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/docs#475]
It would be helpful to have a page that lists the upcoming upgrade heights and estimated time. This information would be used by validators, exchanges, and other partners who want to know when the expect network upgrades. 

* Scheduled Upgrades 
* Block Height
* Estimated time in UTC and user's local timezone. 
* 
This information can be retrieved from `'https://zetachain.blockpi.network/lcd/v1/public/cosmos/upgrade/v1beta1/current_plan'` but ignore the time field.

**Comment by fadeev** [comment]
@CharlieMc0 would it be something similar to https://www.zetachain.com/docs/reference/network/proposals/ ?

**Comment by CharlieMc0** [comment]
Something with more detail and time estimates like this https://polkachu.com/upgrade_history/zetachain 

It can be pulled in using their API - https://polkachu.com/docs/index.html#v2-public-GETapi-v2-chain_upgrades
