### ISSUE TITLE
Update Hosting a Node doc to reflect Athens-3 and have instructions for joining the network.

### ISSUE THREAD

**Issue by btroo** [zeta-chain/docs#5]
Right now, our public docs site has Athens-2 instructions, and the network-athens3 repo only has instructions for joining the network in genesis. We should have a new doc(s) that can get someone from 0 to running a node to joining the Athens-3 network

This is the new repository/file (that will be open sourced) for docs - can either edit this file or create a new file for this: https://github.com/zeta-chain/docs/blob/main/docs/validators/node.md.

**Comment by fadeev** [comment]
Docs now contain info for joining Athens 3.
