### ISSUE TITLE
Mapping of functionality that is live on each connected chain 

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/docs#513]
We should replicate this internal document onto the public docs site to show what functionality is live on each network. 

Internal Link: https://www.notion.so/zetachain/State-of-ZetaChain-Functionality-11b7b3fb9049800fa1bbdb7abc3979c1 (Also attached as a PDF) 

It should also include an explanation of what each feature means and link to examples and tutorials that utilize that function. 

 
[State of ZetaChain Functionality 11b7b3fb9049800fa1bbdb7abc3979c1.pdf](https://github.com/user-attachments/files/17997825/State.of.ZetaChain.Functionality.11b7b3fb9049800fa1bbdb7abc3979c1.pdf)

**Comment by fadeev** [comment]
@CharlieMc0 I think we should make the Notion doc public and post a link to it in the docs. Copying data from the Notion doc into a markdown table is a maintenance nightmare.

**Comment by fadeev** [comment]
We can post a link to the table on https://www.zetachain.com/docs/developers/chains/list/

**Comment by CharlieMc0** [comment]
I was thinking we would ultimately delete the notion doc and work off public docs only so there would be one place to maintain.

**Comment by fadeev** [comment]
@CharlieMc0 like this perhaps:

| Feature                            | Chain   | Mainnet   | Testnet   | E2E   | Localnet   |
|:-----------------------------------|:--------|:----------|:----------|:------|:-----------|
| Deposit/withdraw native coin       | EVM     | ✅        | ✅        | ✅    | ✅         |
| Deposit/withdraw fungible token    | EVM     | ✅        | ✅        | ✅    | ✅         |
| Deposit and call (native coin)     | EVM     | ✅        | ✅        | ✅    | ✅         |
| Deposit and call (fungible token)  | EVM     | ✅        | ✅        | ✅    | ✅         |
| Withdraw and call (native coin)    | EVM     | Dec 2024  | ✅        | ✅    | ✅         |
| Withdraw and call (fungible token) | EVM     | Dec 2024  | ✅        | ✅    | ✅         |
| Deposit ZETA                       | EVM     | ✅        | ✅        | ✅    | ❌         |
| Withdraw ZETA                      | EVM     | ✅        | ✅        | ✅    | ❌         |
| Deposit and call (ZETA)            | EVM     | ❌        | ❌        | ❌    | ❌         |
| Withdraw and call (ZETA)           | EVM     | ❌        | ❌        | ❌    | ❌         |
| Call                               | EVM     | ✅        | ✅        | ✅    | ✅         |
| Deposit/withdraw native coin       | Bitcoin | ✅        | ✅        | ✅    | ❌         |
| Deposit and call (native coin)     | Bitcoin | ✅        | ✅        | ✅    | ❌         |
| Deposit/withdraw native coin       | Solana  | Dec 2024  | ✅        | ✅    | ❌         |
| Deposit/withdraw fungible token    | Solana  | Dec 2024  | Dec 2024  | ❌    | ❌         |
| Deposit and call (native coin)     | Solana  | Dec 2024  | ✅        | ✅    | ❌         |
| Deposit and call (fungible token)  | Solana  | Dec 2024  | Dec 2024  | ❌    | ❌         |
| Withdraw and call (fungible token) | Solana  | ❌        | Feb 25    | ❌    | ❌         |
| Withdraw and call (native coin)    | Solana  | ❌        | Feb 25    | ❌    | ❌         |
| Deposit ZETA                       | Solana  | ❌        | ❌        | ❌    | ❌         |
| Withdraw ZETA                      | Solana  | ❌        | ❌        | ❌    | ❌         |
| Deposit and call (ZETA)            | Solana  | ❌        | ❌        | ❌    | ❌         |
| Withdraw and call (ZETA)           | Solana  | ❌        | ❌        | ❌    | ❌         |
| Call                               | Solana  | ❌        | ❌        | ❌    | ❌         |
| Deposit/withdraw native coin       | TON     | ❌        | ❌        | ✅    | ❌         |
| Deposit/withdraw fungible token    | TON     | ❌        | ❌        | ❌    | ❌         |
| Deposit and call (native coin)     | TON     | ❌        | ❌        | ✅    | ❌         |
| Deposit and call (fungible token)  | TON     | ❌        | ❌        | ❌    | ❌         |
| Withdraw and call (native coin)    | TON     | ❌        | ❌        | ❌    | ❌         |
| Withdraw and call (fungible token) | TON     | ❌        | ❌        | ❌    | ❌         |
| Deposit ZETA                       | TON     | ❌        | ❌        | ❌    | ❌         |
| Withdraw ZETA                      | TON     | ❌        | ❌        | ❌    | ❌         |
| Deposit and call (ZETA)            | TON     | ❌        | ❌        | ❌    | ❌         |
| Withdraw ZETA                      | TON     | ❌        | ❌        | ❌    | ❌         |
| Call                               | TON     | ❌        | ❌        | ❌    | ❌         |

If it looks good, I'll put it in the docs.

**Comment by fadeev** [comment]
HTML may offer more customization options, but I think keeping it simple in an easy to author format is key.

maintainability > looks

**Comment by CharlieMc0** [comment]
Agree on keeping it simple. This works for me.
